version: "3" 
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./var/log/nginx:/var/log/nginx
  elasticsearch:  
    container_name: elasticsearch 
    image: "docker.elastic.co/elasticsearch/elasticsearch:${TAG}"
    ports:
      - "9200:9200" 
    restart: "always"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
     - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
  kibana:  
    container_name: kibana   
    image: "docker.elastic.co/kibana/kibana:${TAG}"
    ports:
      - "5601:5601"   
    restart: "always"   
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  logstash: 
    container_name: logstash  
    image: "docker.elastic.co/logstash/logstash:${TAG}"
    restart: "always"    
    ports:
      - "5044:5044"
      - "5045:5045"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
  filebeat:
    container_name: filebeat
    image: "docker.elastic.co/beats/filebeat:${TAG}" 
    restart: "always"
    volumes:
      - ./var/log:/var/log
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml 
