filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
    # - /var/log/golang/*.log

output.logstash:
  hosts: ["logstash:5044"]

#output.kafka:
#  hosts: [10.200.6.137:9092]
#  topic: "test"
